swagger: '2.0'
info:
  description: |
    Machine Learning Model Attribution Challenge API

    Login on [mlmac.io](https://mlmac.io) with GitHub credentials obtain an API key.
  version: '1.0.0'
  title: 'MLMAC'
  termsOfService: 'https://mlmac.io/terms/'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'api.mlmac.io:8080'
basePath: '/'
tags:
  - name: 'Models'
    description: 'MLMAC models'
  - name: 'User'
    description: 'Operations about user'

schemes:
  - 'https'
  - 'http'
paths:
  /query:
    post:
      tags:
        - 'Models'
      summary: 'Query a model'
      description: ''
      parameters:
        - name: 'model'
          in: 'query'
          description: 'Model identifier from 0 to 11'
          required: true
          type: 'integer'
          minimum: 0
          maximum: 11

        - in: 'body'
          name: 'body'
          description: 'input'
          required: true
          schema:
            $ref: '#/definitions/ModelInput'

      responses:
        200:
          description: Successful model output
          schema:
            $ref: '#/definitions/ModelOutputSuccess'
        401:
          description: Unauthorized, missing Authorization Bearer token in request header
        429:
          description: Too many requests

        500:
          description: Internal server error

        503:
          description: Model is currently loading
          schema:
            $ref: '#/definitions/ModelOutputError'



  /status:
    get:
      tags:
        - 'User'
      summary: 'Query totals and other info'
      description: ''

      responses:
        200:
          description: User stats
          schema:
            $ref: '#/definitions/Status'
        401:
          description: Unauthorized, missing Authorization Bearer token in request header

securityDefinitions:
  bearerAuth: # arbitrary name for the security scheme
    name: 'Authorization'
    in: 'header'
    type: 'apiKey'
    description: 'Use the value of "Bearer your_api_token"'

definitions:
  ModelInput:
    type: 'object'
    properties:
      input:
        type: 'string'
  ModelOutputSuccess:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
          - success
        description: Query status
      result:
        type: 'object'
        properties:
          generated_text:
            type: 'string'
      queries:
        $ref: '#/definitions/Queries'
  ModelOutputError:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
          - failed
        description: Query status
      result:
        type: 'object'
        properties:
          error:
            type: string
            enum:
              - currently loading
          estimated_time:
            type: number
            description: Estimated time in seconds until the model is ready to be queried
      queries:
        $ref: '#/definitions/Queries'
  Queries:
    type: 'object'
    description: String model number to integer number of queries for that model, if greater than 0
    additionalProperties:
      type: 'integer'
    example:
      '1': 9
      '5': 2
  Status:
    type: 'object'
    properties:
      api_key:
        type: string
      name:
        type: string
        description: GitHub username
      created:
        type: string
        description: Date string of when the API key was registered
      total_queries:
        type: integer
      queries:
        $ref: '#/definitions/Queries'

security:
  - bearerAuth: []
